#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#logout:
    #path: /logout
    #defaults: { _controller: 'L3\Bundle\CasBundle\Controller\LogoutController::logoutAction' }
